### ISSUE TITLE
Skip uploading a file if the server already has a file with a matching hash

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#11]
Currently xppf_upload does the file transfer no matter what.

**Comment by nhammond** [comment]
This is implemented in 5fbcb79626693c396ec7debc96ebee8141189950, but with a caveat. Since Google Storage generates the hash at the same time as it does the upload, we upload the file to a temp dir before determining that it already exists. At that point it's deleted. We should consider if it's worth hashing first to prevent wasted uploads.

**Comment by nhammond** [comment]
No more temp uploads. Duplicate upload is be skipped if KEEP_DUPLICATE_FILES is False.
