### ISSUE TITLE
Set worker instances to auto-delete scratch disk

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#214]
Although the Ansible module (http://docs.ansible.com/ansible/gce_pd_module.html) doesn't appear to support this, we can use gcloud or an API call to set instance metadata after the worker is created.

Would prevent orphaned worker disks persisting after instance deletion.

**Comment by nhammond** [comment]
Let's revisit the use of persistent disks vs. boot disk alone. Currently we create a boot disk + a persistent scratch disk. 
- Scratch disks can persist after the instance dies; boot disks cannot. Currently we're not making use of that, and using Docker Volumes may mean that we never want to.
- IO speed for scratch disks varies with disk size and type, which is how we came up with the 163 SSD number (https://cloud.google.com/compute/docs/disks/performance). afaik those constraints don't apply to boot disks, and there is no throttling for smaller boot disks.
- Max size for both boot and persistent disks is 64 TB (raised recently from 10 TB)
- Scratch disks can be writable by one instance, readable by many. That could be useful for files needed by many steps in a workflow. We could potentially copy hg19 from google storage to disk once instead of many times. But again, we're not using that feature currently.

For our current architecture, is there any advantage to using scratch disks?

**Comment by nhammond** [comment]
Please ignore previous deleted comment. Still researching--submitted by accident.

**Comment by isaacliao** [comment]
Implemented in https://github.com/StanfordBioinformatics/loom/commit/a6ec6e7dede67beb03d23b9d93b20c7e4489af29#diff-b82d06ad9408a84b883729cec06cb56aR12
