### ISSUE TITLE
Remove external dependencies from worker deployment

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#56]
Currently we use pip install to create workers. We should avoid this or other things like it (like cloning from our git repo). Worker deployment should depend only on the Loom server installation so that it cannot become out of sync if someone forgets to update a version.

Options we have discussed 
- Create docker image on the fly (but then you need a docker repo)
- Use pip's machinery to deploy but without referring to Pypi repo
- old school tools like rsync or gzip&scp to deploy workers with code from master

**Comment by isaacliao** [comment]
If we download and install to the server using Pip, we won't have the packaging utility (setup.py, which contains the dependencies for installation). That means we'd have to pull it from Git or Pip for the workers.

So the method of deploying to the server affects how we deploy to the workers too. Just wanted to mark that for consideration.

**Comment by isaacliao** [comment]
After thinking about this more, I'd like to present a counterargument. That is, I would like to avoid having to support multiple install methods. Currently we use Pip for end users, server installation is manual (Pip or Git followed by Pip), and worker deployment is done through Pip. 

If we go to a model where users install using Pip, server deployment is manual, and worker installation is rsync'ed directly from the server, we now have to debug and troubleshoot three possible installation methods. I think this would create unnecessary work, and components would get out of sync more easily.

If developers are comfortable creating Pip development releases, this can all be avoided. A developer working on a server would update the version and run two commands: one to package the current working directory, and one to upload to Pip. The server already makes sure to deploy its own version to workers.

We should weigh the risks and benefits carefully before moving away from a version control system.

**Comment by nhammond** [comment]
Does pip imply pypi? Or is there any way to use pip to install code from the server onto the worker, such that we don't add a totally new install process?

**Comment by isaacliao** [comment]
Sure, it looks like this:

On server:
Update VERSION to 0.x.x
Activate virtualenv
Commit changes to Git
python setup.py sdist
Copy dist/loomengine-0.x.x.tar.gz to worker

On worker:
Set up and activate virtualenv
pip install loomengine-0.x.x.tar.gz

Since we're skipping "twine upload", 0.x.x never ends up in PyPI.

Note that here we're assuming the server is cloned from Git. This is for two reasons: first, we need setup.py, and second, we need all files that will be packaged to be checked into Git because we're using setuptools-git (https://pypi.python.org/pypi/setuptools-git). (Without setuptools-git, all non-Python files would need to be declared in a MANIFEST.in, or in a data_files directive: https://docs.python.org/2/distutils/setupscript.html#distutils-additional-files)

**Comment by isaacliao** [comment]
If we start installing Loom without PyPI or GitHub, what about its Python and OS dependencies? We currently use pip and apt-get to install those. In order to not depend on PyPI and Aptitude repositories, we'd have to download and manage local copies of required packages.

I'm going to sound like a broken record, but I think the simplest way to truly not have any external dependencies is to package Loom (and its dependencies) in a Docker image. 

Also, note that a Docker repo is NOT needed to build Docker images and ship them. We could use `docker save` to save an image to a .tar file, copy it to the destination (server or worker instance), then load it with `docker load`: http://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-via-repository

**Comment by nhammond** [comment]
Obsolete issue. We are now consistently using Docker to deploy server or worker, whether local or remote.
